export enum StaffType{
  TCAE = "TCAE",
  NURSE = "NURSE",
  FISIO = "FISIO",
  SPEECH_THERAPIST = "SPEECH_THERAPIST",
  OCCUPATIONAL_THERAPY = "OCCUPATIONAL_THERAPY",
  TEAP = "TEAP", 
  TEDN = "TEDN", 
  TEDS = "TEDS", 
  TEL = "TEL", 
  TEMN = "TEMN", 
  TERD = "TERD", 
  TER = "TER", 
  TF = "TF"
}
