export enum StaffSpecificJobBankType{
  NURSE_CRITICS = "NURSE_CRITICS",
  NURSE_DIALYSIS = "NURSE_DIALYSIS",
  NURSE_MENTAL_HEALTH = "NURSE_MENTAL_HEALTH",
  NURSE_NEONATES = "NURSE_NEONATES",
  NURSE_NUCLEAR = "NURSE_NUCLEAR",
  NURSE_SURGERY_ROOM = "NURSE_SURGERY_ROOM"
}
