export enum StaffJobBankType{
  TCAE = "TCAE",
  NURSE = "NURSE",
  FISIO = "FISIO",
  SPEECH_THERAPIST = "SPEECH_THERAPIST",
  OCCUPATIONAL_THERAPY = "OCCUPATIONAL_THERAPY",
  NURSE_FAMILY = "NURSE_FAMILY",
  NURSE_GYNECOLOGY = "NURSE_GYNECOLOGY",
  NURSE_PEDIATRICIAN = "NURSE_PEDIATRICIAN",
  NURSE_MENTAL_HEALTH = "NURSE_MENTAL_HEALTH",
  NURSE_WORK = "NURSE_WORK"
}
